use crate::ast::*;
grammar;

match {
    r"\s*" => {},
    r"//[^\n\r]*[\n\r]*" => {},

    _
}

pub CompUnit: CompUnit = <func_def: FuncDef> => CompUnit{<>};

pub FuncDef: FuncDef = <func_type: FuncType> <ident: Ident> "(" ")" <block: Block> => FuncDef {<>};

pub Block: Block = "{" <stmt: Stmt> "}" => Block{<>};

pub FuncType: FuncType = "int" => FuncType::Int;

pub Stmt: Stmt = "return" <num: Number> ";" => Stmt{<>};

pub Ident: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

pub Number: i32 =  {
    r"[1-9][0-9]*" => i32::from_str_radix(<>, 10).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
}